config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}


  resources :portfolios, except: [:show] do
         put :sort, on: :collection
  end
 

  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'portfolios/:id', to: 'portfolios#show'

  get 'angular-items', to: 'portfolios#angular'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do 
      get :toogle_status
    end
  end
 
  mount ActionCable.server => '/cable'
  
  root to: 'pages#home'

  
end
 # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/blog.rb
class Blog < ApplicationRecord
    enum status: {draft: 0, published: 1 }
    extend FriendlyId
    friendly_id :title, use: :slugged

    validates_presence_of :title, :body

    belongs_to :topic, optional: true

    has_many :comments, dependent: :destroy
    
    def self.special_blogs
        all
    end

    def self.featured_blogs
        limit(2)
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toogle_status]

  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :toogle_status]}, site_admin: :all

  layout "blog"

  # GET /blogs
  # GET /blogs.json
  def index
    # byebugPuser.
    @blogs = Blog.page(params[:page]).per(5)
    # @blogs = Blog.featured_blogs
    @page_title = "My Portfolio blog."
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog = Blog.includes(:comments).friendly.find(params[:id])
    @comment = Comment.new
    @page_title = @blog.title
    # @ser_keywords = @blog.body
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toogle_status
    # byebug
    if @blog.draft?
      @blog.published!
    elsif @blog.published!
      @blog.draft!
    end
    redirect_to blogs_url, notice: 'Post status has been updated'
 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
<div class="blog-post">
   
    <h2 class="blog-post-title"><%= link_to blog.title.upcase, blog %></h2>
     <p class="blog-post-meta">Published <%= distance_of_time_in_words(blog.created_at, Time.now ) %>"ago."</p>

    <% if logged_in?(:site_admin) %>
        <p class="blog-post-meta">
        <%= link_to blog.status, toogle_status_blog_path(blog) %> / <%= link_to 'Edit', edit_blog_path(blog) %> / <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' }%>
        </p>
    <% end %>
   
    <p>
        <%= blog.body %> 
    </p>

</div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %> 
     
    <% blog.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= form.text_field :title, class: 'form-control', placeholder: "Title" %>
  </div>

  <div class="form-group">
    <%= form.text_area :body, class: 'form-control', rows: 15, placeholder: "Content" %>
  </div>

  <div class="form-group">
    <%= form.submit "Submit", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="col-sm-8 blog-main">
<h1>Editing Blog</h1> 

    <%= render 'form', blog: @blog %>

    <%= link_to 'Show', @blog %> |
    <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/index.html.erb
<div class="col-sm-8 blog-main">

  <%= paginate @blogs %>
  
  <%= render @blogs %>

  <%= paginate @blogs %>

</div>

app/views/blogs/new.html.erb
<div class="col-sm-8 blog-main">
    <h1>New Blog</h1>

    <%= render 'form', blog: @blog %>

    <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/show.html.erb
<div class="col-sm-8 blog-main">
  <h2> <%= @blog.title %></h2>
  <p>
    <%= @blog.body %> <br>
    <%= link_to 'Edit', edit_blog_path(@blog) if logged_in?(:site_admin)%> /
     <%= link_to 'Delete', blog_path(@blog), method: :delete,  data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %>
  </p>

  <%= render 'comments/comment_form'%>
  <div id="comments" data-blog-id="<%= @blog.id%>">
    <%= render @blog.comments %>
  </div>
</div>

 