config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}


  resources :portfolios, except: [:show] do
         put :sort, on: :collection
  end
 

  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'portfolios/:id', to: 'portfolios#show'

  get 'angular-items', to: 'portfolios#angular'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do 
      get :toogle_status
    end
  end
 
  mount ActionCable.server => '/cable'
  
  root to: 'pages#home'

  
end
 # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/portfolio.rb
class Portfolio < ApplicationRecord
    has_many :technologies
    accepts_nested_attributes_for :technologies,
                                   reject_if: lambda {|attrs|attrs['name'].blank? }


    include Placeholder
    validates_presence_of :title, :body

    # this requires carrierwave gem
    mount_uploader :thumb_image, PortfolioUploader
    mount_uploader :main_image, PortfolioUploader

    def self.angular
        where(subtitle: "Angular")
    end

    scope :ruby_on_rails_portfolio_items, -> {where(subtitle: 'Ruby On Rails')}

    def self.by_position
        order("position ASC")
    end



    # acts_as_list scope: :circuit
    default_scope { order(position: :asc) }






end
 

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
    before_action :set_portfolio_item, only: [:edit, :show, :update, :destroy]
    access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all
    layout "portfolio"

    def index
      @portfolio_items = Portfolio.order(:position)
        # @portfolio_items = Portfolio.ruby_on_rails_portfolio_items
    end

    def sort
      params[:order].each do |key, value|
        Portfolio.find(value[:id]).update(position: value[:position])
      end
  
      render nothing: true
    end

    def angular
      @angular_items = Portfolio.angular
      # byebug
    end

    def new
        @portfolio_item = Portfolio.new
        # 3.times { @portfolio_item.technologies.build}
    end

    def create
      # byebug
        @portfolio_item = Portfolio.new(portfolio_params)
        respond_to do |format|
            if @portfolio_item.save
              format.html { redirect_to @portfolio_item, notice: 'portfolio_item was successfully created.' }
              format.json { render :show, status: :created, location: @portfolio_item }
            else
              format.html { render :new }
              format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
            end
          end
    end

    def show
      
    end

    def edit
    end

    def update
        respond_to do |format|
          if @portfolio_item.update(params.require(:portfolio).permit(:title, :subtitle, :body))
            format.html { redirect_to portfolios_path, notice: 'portfolio_item was successfully updated.' }
            format.json { render :show, status: :ok, location: @portfolio_item }
          else
            format.html { render :edit }
            format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
          end
        end
      end

      def destroy
        @portfolio_item.destroy
        
        respond_to do |format|
          format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully destroyed.' }
          format.json { head :no_content }
        end
      end



    private
    # Use callbacks to share common setup or constraints between actions.
    def portfolio_params
      params.require(:portfolio).permit(:title, 
                                        :subtitle, 
                                        :body,
                                        :main_image,
                                        :thumb_image,
                                        technologies_attributes: [:id, :name, :_destroy])
    end

    def set_portfolio_item
      @portfolio_item = Portfolio.find(params[:id])
    end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
    def image_generator(height:, width:)
        "http://placehold.it/#{height}x#{width}"
      end
    
      def portfolio_img img, type
        if img.model.main_image? || img.model.thumb_image?
          img
        elsif type == 'thumb'
          image_generator(height: '350', width: '200')
        elsif type == 'main'
          image_generator(height: '600', width: '400')
        end
      end

end


# self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
# self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')

app/views/portfolios/_form.html.erb
<%= form_with(model: @portfolio_item, local: true) do |form| %>
  <% if @portfolio_item.errors.any? %>
    <div id="error_explanation">
        <% @portfolio_item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :subtitle %>
        <%= form.text_field :subtitle, class: 'form-control' %>
      </div>
   

    <div calss="form-group">
      <%= form.file_field :main_image %>
    </div>
    <div calss="form-group">
      <%= form.file_field :thumb_image %>
    </div>
  </div>
    <div class="col-md-6">
        <div class="form-group">
        <%= form.label :body %>
        <%= form.text_area :body, class: 'form-control', rows: 13 %>
      </div>
    </div>
  </div>

  <hr>
  <div class="col-md-12">
      <%# <h2>Techs Used:</h2>
      <div>
        <%= form.fields_for :technologies do |technology_form|%>
           <%# <%= render "technology_fields", f: technology_form %>
        <%# <% end %> 
        <%# <div>
          <%= link_to_add_association 'Add Tech', form, :technologies %>
        <%# </div>
    </div> %> 

      <div class="form-group">
        <%= form.submit 'Save Portfolio Item', class:'btn btn-primary btn-block' %>
      </div>
    <% end %>

    <%# <% if logged_in?(:site_admin) %>
      <%# <div class="">
        <%= link_to 'Edit Item', edit_portfolio_path(@portfolio_item), class: 'btn btn-warning' %>
      <%# </div>
      <% end %>
  </div>

app/views/portfolios/_portfolio_item.html.erb
  <div class="card thumb_image_size">

    <% if portfolio_item.thumb_image? %>
      <%= image_tag portfolio_item.thumb_image.url, width: '100%'  unless portfolio_item.thumb_image.nil?%> 
    <%end %>
 
    <p class="card-text">
     <span><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></span> 
      <%= portfolio_item.subtitle %>
 
     <div class="row">

      <% if logged_in?(:site_admin) %>  
       &nbsp;&nbsp;&nbsp;<%= link_to 'Edit', edit_portfolio_path(portfolio_item) %> &nbsp; / &nbsp;
       <%= link_to 'Destroy', portfolio_item, method: :delete,  data: { confirm: 'Are you sure?' }%>
      <% end %>
     </div>
     </p>
   
  </div>


  <%# <%= image_tag portfolio_img(portfolio_item.thumb_image, 'thumb') %>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', rows: 15 %>
    <%= link_to_remove_association "Remove Tech", f %>
</div>

app/views/portfolios/angular.html.erb
<h1>Angular page of Portfolio</h1>
<%= link_to "Create New Item", new_portfolio_url if logged_in?(:site_admin) %>

<% @angular_items.each do |portfolio_item| %>
    <h1><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></h1>
        <p><%= portfolio_item.subtitle %></p>
        <p><%= portfolio_item.body %></p>
        <%= image_tag portfolio_item.thumb_image if !portfolio_item.thumb_image.nil? %>
        <%= link_to "Edit", edit_portfolio_path(portfolio_item) if logged_in?(:site_admin)%>
        <%= link_to "Delete Angular Item", portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin)%>
<% end %>

app/views/portfolios/edit.html.erb
 
<div class="container">
    <h1>Edit this Portfolio Item</h1>

    <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div class="album text-muted jack">
  <div class="container">
     <%= link_to 'Create New Post', new_portfolio_path(@portfolio_item), class:'btn btn-primary' %>
    <div id="portfolios" class="row sortable" data-url="<%= sort_portfolios_path %>">
    <div class="thumb_image_size">
      <%= render partial: 'portfolio_item', collection: @portfolio_items %>
    </div>
    </div>
  </div>
</div>


  <%= javascript_pack_tag 'portfolios' %>

app/views/portfolios/new.html.erb
<div class="container">

    <h1>Create a new Portolio Item</h1>

    <%= render 'form', portfolio_item: @portfolio_item %>
    
</div>

app/views/portfolios/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-7">
        <div class="main_image_size">
            <%= image_tag @portfolio_item.main_image.url, width: '100%' %> 
             <%# <%= image_tag portfolio_img(@portfolio_item.main_image, 'main'), width: '100%' %> 
        </div>
        </div>
        <div class="col-md-5">
            <h1><%= @portfolio_item.title %></h1>

            <em><%= @portfolio_item.subtitle %></em>

            <p><%= @portfolio_item.body %></p>

            <%# <h2>Technologies Used:</h2> %>

            <%# <% @portfolio_item.technologies.each do |f| %>
            <%# <p><%= f.name %></p>
            <%# <% end %> 
        </div>
    </div>

</div>