config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}


  resources :portfolios, except: [:show] do
         put :sort, on: :collection
  end
 

  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'portfolios/:id', to: 'portfolios#show'

  get 'angular-items', to: 'portfolios#angular'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do 
      get :toogle_status
    end
  end
 
  mount ActionCable.server => '/cable'
  
  root to: 'pages#home'

  
end
 # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/views/shared/_alerts.html.erb
<% if flash[:alert] %>
    <%= js add_gritter(flash[:alert], :title => "Jack Portfolio!") %>
<% elsif flash[:error] %>
    <%= js add_gritter(flash[:error], :title => "Jack Portfolio!") %>
<% else %>
    <%= js add_gritter(flash[:notice], :title => "Jack Portfolio!") %>
<% end %>

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
  <div class="inner">
    <p><%= copyright_generator %></p>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand">Jack Van</h3>
    <nav class="nav nav-masthead">
      <%= render "shared/shared_nav_main"%>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
  <footer class="blog-footer">
          <p>
            <%= copyright_generator %>
          </p>
          <p>
            <a href="#">Back to top</a>
          </p>
</footer>

app/views/shared/_blog_masthead.html.erb
 <div class="blog-header">
      <div class="container">
        <h1 class="blog-title">My Blog</h1>
        <p class="lead blog-description">Blog template built upon Rails and Jquery/Action Cable.</p>
        <%= link_to 'Write A New Blog', new_blog_path if logged_in?(:site_admin) %>
      </div>
</div>

app/views/shared/_blog_nav.html.erb
<div class="blog-masthead">
      <div class="container">
        <nav class="nav blog-nav app-nav">
            <%= render "shared/shared_nav_main"%>
            <%= login_helper 'nav-link' %>
        </nav>
      </div>
</div>

app/views/shared/_blog_sidebar.html.erb
  <div class="col-sm-3 offset-sm-1 blog-sidebar">
    <div class="sidebar-module sidebar-module-inset">
        <h4>About</h4>
        <p>Eager to develope meaningful apps <em>with implementing good web develping technique and so on.</em></p>
    </div>
 
    <div class="sidebar-module">
        <h4>Elsewhere</h4>
         <ol class="list-unstyled social-links">
                <li><a href="https://github.com/VanBawi"><%= fa_icon "github" %></a></li>
                <li><a href="https://www.instagram.com/jackte1500/"><%= fa_icon "instagram" %></a></li>
                <li><a href="https://www.facebook.com/jack.te.9"><%= fa_icon "facebook" %></a></li>
                <%# <li><a href=""><%= fa_icon "twitter" %></a></li> 
        </ol>
    </div>
    </div>

app/views/shared/_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <p>
    <%= copyright_generator %>
    </p>
  </div>
</footer>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
    <div><%= link_to "Home", root_path %></div>
    <div><%= link_to "About", about_me_path %></div>
    <div><%= link_to "Contact", contact_path %></div>
    <div><%= link_to "Blog", blogs_path %></div>
    <div><%= link_to "Portfolio", portfolios_path %></div>
</div>

app/views/shared/_portfolio_footer.html.erb
<!-- start of footer -->
<footer class="text-muted">
    <div class="container">
    <p class="float-right">
        <%= link_to 'View all my portfolios', portfolios_path %>
        <a href="#">Back to top</a>
    </p>
    <p>
        <%= copyright_generator %>
    </p>
    </div>
</footer>
    <!-- end of footer -->

app/views/shared/_portfolio_masthaed.html.erb
<!-- start of masthead -->
  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">My Portfolio</h1>
      <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
      <p>
        <%= link_to 'Find out more about me.', about_me_path, class: 'btn btn-primary'%>
          <%= link_to 'My Blog', blogs_path, class: 'btn btn-secondary'%>
      </p>
    </div>
  </section>
<!-- end of masthead -->

app/views/shared/_portfolio_nav.html.erb
<div class="blog-masthead">
      <div class="container nav-right">
        <nav class="nav blog-nav button">
            <%= render "shared/shared_nav_main"%>
            <%= login_helper 'nav-link btn-color' %>
        </nav>
      </div>
    </div>




<style>
.nav-right{
    display: flex;
    justify-content: flex-end !important;
}

.button {
    color: white;
    font-weight: bold;
    border-bottom-color: #fff;
    
    
}
.btn-color:hover{
    /* margin-right: 3px; */
    border-radius: 3px;
    background-color: #296e84;
    padding-bottom: -3px solid #fff;
    cursor: pointer;
}

.button .btn-color:hover,
.button .btn-color:focus{
    border-bottom-color: #fff;
}

</style>

app/views/shared/_shared_nav_main.html.erb
<%= link_to "Home", root_path, class: "nav-link #{active? root_path}" %>
<%= link_to "About Me", about_me_path, class: "nav-link #{active? about_me_path}" %>
<%= link_to "Contact", contact_path, class: "nav-link #{active? contact_path}" %>
<%= link_to "Blog", blogs_path, class: "nav-link #{active? blogs_path}" %>
<%= link_to "Portfolio", portfolios_path, class: "nav-link #{active? portfolios_path}" %>